### PR TITLE
removed Hashtable and type-unsafe properties

### PR DESCRIPTION
**Pull request by krichter722**
This is WIP. I don't mind someone telling be why dragging suddenly no longer works.

The idea is avoid type-unsafe operations as often as possible since they are error sources. `Hashtable` is an obsolete collection.

### CODE REVIEW

**Comment by sylvestre** [comment]
Needs rebasing

**Comment by krichter722** [comment]
> Needs rebasing

I'll do that, but regardless of that, can you maybe document `PropertyManager` since I'd like to figure out whether it's an improvement to remove it or not worth considering it. I hope you find the small amount of energy to do that for an inactive project.

**Comment by sylvestre** [comment]
AFAIK, Scilab is making the most important usage of this library. They might have an opinion cc @TotoYasp  @davidcl

**Comment by calixteman** [comment]
As an advice, you can download scilab (or compile it if you prefer) and replace the flexdock jar file by yours and check if there are some regressions.

**Comment by krichter722** [comment]
> As an advice, you can download scilab (or compile it if you prefer) and replace the flexdock jar file by yours and check if there are some regressions.

Good advise, but I already see from the demo that dragging isn't started. I guess the difference between the outcome and the effort is too large. I'll leave this open until someone has resources to have a look or is annoyed of the open PR.

**Comment by sylvestre** [comment]
not action for a while, closing!

**Pull request closed without merging**
