### PR TITLE
Migrated to maven:

### PR DESCRIPTION
**Pull request by krichter722**
- subprojects flexdock-core, flexdock-demo, flexdock-drag, flexdock-perspective
  and flexdock-view are the minimal set of subprojects (view and plaf depend on
  each other; flexdock-view dynamically loads classes from flexdock-dockbar which
  introduces a dependency cycle)
- pom.xml might not cover all functionality of build.xml like signing, copying
  demo jars to source root (which is quite uncommon for maven projects anyway) and
  creating webstart files
- removed IDE specific files like .classpath and .project and .iml files (maven
  is so portable that popular IDEs (like NetBeans, Eclipse and Intellij) should
  handle projects without those and IDE-agnostic project setup is more
  sophisticated)
- moved integration tests with main methods which require a display and other
  integration test resources to flexdock-demo project in order to avoid execution
  in travis and because it's a better arrangement

### CODE REVIEW

**Comment by krichter722** [comment]
I'd appreciate if you'd turn on travis-ci.org and check this PR since I'm not 100 % sure whether travis-ci.org did understand that krichter722/flexdock has been deleted and then used as name for the fork, [apparently it passes](https://travis-ci.org/krichter722/flexdock/builds/170177033).

**Comment by sylvestre** [comment]
I just configured it, I don't know how to retrigger it. Could you make a small change in the PR to force it?

**Comment by krichter722** [comment]
> I just configured it, I don't know how to retrigger it. Could you make a small change in the PR to force it?

You can use `git commit --amend && git push --force` without changes in this case :)

**Comment by sylvestre** [comment]
Could you just update https://github.com/opencollab/flexdock/blob/master/release-notes.txt ?

**Comment by sylvestre** [comment]
Could you also update README-BUILD ?

**Comment by krichter722** [comment]
> Could you just update https://github.com/opencollab/flexdock/blob/master/release-notes.txt ?

I'm not a good version philosopher. I made it 1.3 since it's a severe change, but no functional change, so it's not too clear to me. If you're ok with it, you can add a `git` tag.

> Could you also update README-BUILD ?

Done.

**Comment by sylvestre** [comment]
1.3 make senses. 
I will tag it after (and we will release it right after with your great work)

**Pull request merged**
